name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-Latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
        logout: true
    - name: Criar e enviar imagem Docker
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: |
          mpsouza27/kube-news:${{ github.run_number }}
          mpsouza27/kube-news:latest
  CD:
    runs-on: ubuntu-Latest
    needs: [CI]
    steps:
    - name: Authenticar na AWS
      run: echo "authenticar na AWS"
      
     
    
